# Site settings
title: IP Geo Block
description: A WordPress Geo-blocking plugin with Zero-day Exploit Prevention
# A WordPress plugin that will blocks any comment, pingback and 
# trackback spams posted from outside your nation.
# And it will also protect against malicious access to the login form, admin 
# area and XML-RPC from undesired countries with zero-day exploit prevention.

# base url and sub path
# for local: jekyll serve --drafts --baseurl '' --incremental --watch
baseurl: "https://www.ipgeoblock.com"

permalink: none

# Paginate
recent_post: 5
paginate: 5
paginate_path: "/blog/:num/"

exclude: [README.md]

project:
  name: "Wordpress-ip-geo-block"

excerpt_separator: "<!--more-->"

# for jekyll 3
# make sure https://github.com/github/pages-gem
gems: [jekyll-paginate]
plugins_dir:
  - jekyll-paginate

# Build settings (jekyll 2.5.3: pygments, jekyll 3.0: rouge)
# highlighter: pygments # rouge
# markdown: redcarpet

# extensions for GitHub Flavored Markdown
# pygments:
#   options: ["startinline"]
# redcarpet:
#   extensions: [
#     "no_intra_emphasis",            # not apply em to foo_bar_baz
#     "tables",                       # enable tables
#     "fenced_code_blocks",           # enable ```
#     "autolink",                     # enable auto link
#     "disable_indented_code_blocks", # disable code block with spaces
#     "strikethrough",                # del tag with ~~
#     "superscript"                   # use sup ex: 2^n
#   ]

# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# Codex
collections:
  codex:
    output: true
    permalink: /codex/:title.html

# Google Analytics (tokkonopapa@gmail.com)
google_analytics_tracking_id: UA-42366765-2 

author: tokkonopapa
email: tokkonopapa@yahoo.com

twitter_username: tokkonoPapa
github_username:  tokkonopapa
